
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: EcommerceDb
      POSTGRES_USER: Norhan
      POSTGRES_PASSWORD: Norhan@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "Norhan"]
      interval: 10s
      retries: 5
      start_period: 10s

  aspnet_app:
    image: ecommerceweb
    container_name: Ecommercecontainer
    build:
      context: .
      dockerfile: Ecommerce.Web/Dockerfile
    environment:
     - DB_HOST=postgres_db
     - DB_NAME=EcommerceDb
     - DB_USER=Norhan
     - DB_PASS=Norhan@123
     - ASPNETCORE_URLS=http://+:80 
    depends_on:
       postgres_db:
        condition: service_healthy
           
    ports:
      - "5000:80"

volumes:
  postgres_data:
